import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Foter} from "@/components/Footer/footter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TecnoWorld",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Foter />
      </body>
    </html>
  );
}
